INSERT INTO professor (`EMP_NUM`, `EMP_FNAME`, `EMP_LNAME`, `EMP_DOB`, `DEPT_CODE`, `PROF_EXTENSION`) VALUES
(101, 'Charles', 'Xavier' , '1945-05-04 00:00:00', 'CIS' , NULL),
(702, 'Stephen', 'Strange', '1988-07-04 00:00:00', 'BIOL' , '7702');

INSERT INTO student (`STU_NUM`, `STU_FNAME`, `STU_LNAME`, `STU_DOB`, `STU_CLASS`, `STU_GPA`, `DEPT_CODE`, `EMP_NUM`) VALUES
(773355,'Wasin','Heesawat','2000-07-29 00:00:00','3','3.00','CIS' , 702);

UPDATE student
SET EMP_NUM = 101
WHERE STU_NUM = 773355;

UPDATE professor
SET PROF_EXTENSTION = 0077
WHERE EMP_NUM = 101;

DELETE FROM professor
WHERE EMP_NUM = 702;

SELECT *
FROM student;

SELECT EMP_FNAME,EMP_LNAME,DEPT_CODE
FROM professor
WHERE DEPT_CODE = 'CIS';

SELECT EMP_FNAME,EMP_LNAME
FROM professor
WHERE EMP_FNAME LIKE "%M%" AND EMP_LNAME LIKE "%M%";

SELECT STU_NUM,STU_FNAME,DEPT_CODE
FROM student
WHERE DEPT_CODE IN ("ART","ENG","HIST","SOC") 
ORDER BY DEPT_CODE ASC;

SELECT COURSE_CODE,COURSE_NAME,(CRS_CREDIT*250) AS TUITION_FEE,DEPT_CODE
FROM course
WHERE COURSE_NAME LIKE "INTRO.%"
ORDER BY DEPT_CODE ASC;

SELECT distinct COURSE_CODE , CLASS_ROOM
FROM class
WHERE (CLASS_CODE BETWEEN 20000 AND 30000 AND CLASS_ROOM LIKE "KLR%");